version: '3'
services:

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - //usr/local/hass/config:/config
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host

  esphome:
    container_name: esphome
    image: "esphome/esphome"
    volumes:
      - //usr/local/hass/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
