esphome:
  name: "cr-panel"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "N/l08dANbmZ7QKSbdQf0Qqf/PkYrfV+ug00qqo9hK1E="

ota:
  password: "a8b70aad48831c0345a7313574ba67ee"

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi2_ssid
      password: !secret wifi2_password 
  
  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "CR Panel Fallback Hotspot"
    password: "mfAzq47fxZoB"

captive_portal:

# Include custom fonts
font:
  - file: 'fonts/GothamRnd-Bold.ttf'
    id: font1
    size: 65

  - file: 'fonts/GothamRnd-Bold.ttf'
    id: font2
    size: 28

  - file: 'fonts/GothamRnd-Bold.ttf'
    id: font3
    size: 24

  - file: 'fonts/GothamRnd-Bold.ttf'
    id: font4
    size: 10


color:
  - id: color_fg
    red: 0%
    green: 0%
    blue: 0%
    white: 50%
  - id: color_bg
    red: 0%
    green: 0%
    blue: 0%
    white: 0%

sensor:

  - platform: wifi_signal
    name: "CR Panel WiFi"
    id: wifisignal
    update_interval: 60s

text_sensor:

  - platform: homeassistant
    entity_id: sensor.center_projector_status
    id: center_projector_status

  - platform: homeassistant
    entity_id: sensor.stage_left_projector_status
    id: stage_left_projector_status

  - platform: homeassistant
    entity_id: sensor.stage_right_projector_status
    id: stage_right_projector_status
    
  - platform: homeassistant
    entity_id: sensor.first_reading
    id: readings_first
    
  - platform: homeassistant
    entity_id: sensor.psalm
    id: readings_psalm
    
  - platform: homeassistant
    entity_id: sensor.second_reading
    id: readings_second
    
  - platform: homeassistant
    entity_id: sensor.gospel
    id: readings_gospel
    
  - platform: homeassistant
    entity_id: sensor.mass_headline
    id: mass_headline

# Pins for Waveshare ePaper ESP Board
spi:
  clk_pin: GPIO13
  mosi_pin: GPIO14

time:
  - platform: homeassistant
    timezone: America/Los_Angeles
    id: esptime
    
    on_time:
    - seconds: 0
      minutes: /1
      then:
        - component.update: eink

# Now render everything on the ePaper screen. 800x480
display:
  - platform: waveshare_epaper
    id: eink
    cs_pin: GPIO15
    dc_pin: GPIO27
    busy_pin: GPIO25
    reset_pin: GPIO26
    model: 7.50inV2
    update_interval: 3600s
    rotation: 180°
    lambda: |-
      it.fill(color_bg);

      it.strftime(400, 0,   id(font1), color_fg, TextAlign::TOP_CENTER, "%A %b %d, %Y", id(esptime).now());
      it.strftime(400, 60, id(font1), color_fg, TextAlign::TOP_CENTER, "%l:%M %p", id(esptime).now());
      
      it.print(280, 130, id(font2), color_fg, TextAlign::TOP_RIGHT, "Headline: ");
      it.print(280, 160, id(font2), color_fg, TextAlign::TOP_RIGHT, "First Reading: ");
      it.print(280, 190, id(font2), color_fg, TextAlign::TOP_RIGHT, "Psalm: ");      
      it.print(280, 220, id(font2), color_fg, TextAlign::TOP_RIGHT, "Second Reading: ");     
      it.print(280, 250, id(font2), color_fg, TextAlign::TOP_RIGHT, "Gospel: "); 

      it.print(280, 130, id(font2), color_fg, TextAlign::TOP_LEFT, id(mass_headline).state.c_str());      
      it.print(280, 160, id(font2), color_fg, TextAlign::TOP_LEFT, id(readings_first).state.c_str());
      it.print(280, 190, id(font2), color_fg, TextAlign::TOP_LEFT, id(readings_psalm).state.c_str());      
      it.print(280, 220, id(font2), color_fg, TextAlign::TOP_LEFT, id(readings_second).state.c_str());     
      it.print(280, 250, id(font2), color_fg, TextAlign::TOP_LEFT, id(readings_gospel).state.c_str()); 
 
      
      it.print(280, 330, id(font2), color_fg, TextAlign::TOP_RIGHT, "On Air: ");  
      it.print(280, 330, id(font2), color_fg, TextAlign::TOP_LEFT, (id(vmix_on_air).state)?"True":"False");      

      it.print(650, 290, id(font2), color_fg, TextAlign::TOP_RIGHT, "Stage Left: ");
      it.print(650, 320, id(font2), color_fg, TextAlign::TOP_RIGHT, "Center: ");
      it.print(650, 350, id(font2), color_fg, TextAlign::TOP_RIGHT, "Stage Right: ");
      
      it.print(650, 290, id(font2), color_fg, TextAlign::TOP_LEFT, id(stage_left_projector_status).state.c_str());
      it.print(650, 320, id(font2), color_fg, TextAlign::TOP_LEFT, id(center_projector_status).state.c_str());
      it.print(650, 350, id(font2), color_fg, TextAlign::TOP_LEFT, id(stage_right_projector_status).state.c_str());
      
      it.print(600, 380, id(font3), color_fg, TextAlign::TOP_CENTER, "(Wait 1 Min For Update)");

      it.print(510, 420, id(font3), color_fg, TextAlign::TOP_CENTER, "Projectors");
      it.print(710, 420, id(font3), color_fg, TextAlign::TOP_CENTER, "Projectors");
      
      it.print(510, 450, id(font3), color_fg, TextAlign::TOP_CENTER, "On");
      it.print(710, 450, id(font3), color_fg, TextAlign::TOP_CENTER, "Off");

binary_sensor:

  - platform: homeassistant
    entity_id: binary_sensor.vmix_on_air
    id: vmix_on_air

  - platform: gpio
    pin:
      number: GPIO17
      inverted: true
      mode:
        input: true
        pullup: true
    name: AV Panel Button 1
    id: av_panel_button1
    filters:
      - delayed_on: 125ms
      - delayed_off: 125ms
      - delayed_on_off: 125ms
    on_press:
      then:
      - homeassistant.service:
          service: switch.turn_off
          data:
            entity_id: switch.stage_right_projector_state, switch.center_projector_state, switch.stage_left_projector_state
      - delay: 5s
      - component.update: eink
            

  - platform: gpio
    pin:
      number: GPIO22
      inverted: true
      mode:
        input: true
        pullup: true
    name: AV Panel Button 2
    id: av_panel_button2
    filters:
      - delayed_on: 125ms
      - delayed_off: 125ms
      - delayed_on_off: 125ms
    on_press:
      then:
      - homeassistant.service:
          service: switch.turn_on
          data:
            entity_id: switch.stage_right_projector_state, switch.center_projector_state, switch.stage_left_projector_state
      - delay: 5s
      - component.update: eink

  - platform: gpio
    pin:
      number: GPIO18
      inverted: true
      mode:
        input: true
        pullup: true
    name: AV Panel Button 3
    id: av_panel_button3
    filters:
      - delayed_on: 125ms
      - delayed_off: 125ms
      - delayed_on_off: 125ms

  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    name: AV Panel Button 4
    id: av_panel_button4
    filters:
      - delayed_on: 125ms
      - delayed_off: 125ms
      - delayed_on_off: 125ms
