esphome:
  name: fc-door1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "6R9KdHv9vHxigHu5tsO6fj8S2qdP45IKnkUybBObNiA="

ota:
  password: "8ebd1795d1e4f8cfdbfa897241399662"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fc-Door1 Fallback Hotspot"
    password: "xB7lgkRUR0hA"

captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "FcDoor1 WiFi"
    update_interval: 60s
    
binary_sensor:
  - platform: gpio
    pin:
      number: 4
      inverted: false
      mode:
        input: true
        pullup: true
    name: FC Door 1
    id: fc_door1
    filters:
      - delayed_on: 125ms
      - delayed_off: 125ms
      - delayed_on_off: 125ms

  - platform: gpio
    pin:
      number: 5
      inverted: false
      mode:
        input: true
        pullup: true
    name: FC Door 2
    id: fc_door2
    filters:
      - delayed_on: 125ms
      - delayed_off: 125ms
      - delayed_on_off: 125ms
      

