esphome:
  name: gym-lights
  includes:
    - IoBoard.h

esp8266:
  board: esp01_1m

# Enable Home Assistant API
api:
  encryption:
    key: "kO3vOhGOpjPuieZWqwctzOMJSC2dIEX7z8K5DxXAN28="

ota:
  password: "d4779bc1fd716612ab8013d2966a31f3"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gy-Lights Fallback Hotspot"
    password: "YD8Ue3i3tXmJ"

captive_portal:

custom_component:
  - id: ioboard
    lambda: |-
      auto iob_component = new IoBoard();
      App.register_component(iob_component);
      return {iob_component};

sensor:
  - platform: wifi_signal
    name: "GyLights WiFi"
    update_interval: 60s
 
switch:

  - platform: custom
    lambda: |-
      return { iobGetSwitch(ioboard, 6), iobGetSwitch(ioboard, 4),  iobGetSwitch(ioboard, 2),
               iobGetSwitch(ioboard, 0), iobGetSwitch(ioboard, 10), iobGetSwitch(ioboard, 8),
               iobGetSwitch(ioboard, 7), iobGetSwitch(ioboard, 5),  iobGetSwitch(ioboard, 3),
               iobGetSwitch(ioboard, 1), iobGetSwitch(ioboard, 11), iobGetSwitch(ioboard, 9) };

    switches:

      - id: gym_lights0_on
        name: "Gym Lights 0 On"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights0_on

      - id: gym_lights1_on
        name: "Gym Lights 1 On"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights1_on

      - id: gym_lights2_on
        name: "Gym Lights 2 On"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights2_on

      - id: gym_lights3_on
        name: "Gym Lights 3 On"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights3_on

      - id: gym_lights4_on
        name: "Gym Lights 4 On"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights4_on

      - id: gym_lights5_on
        name: "Gym Lights 5 On"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights5_on

      - id: gym_lights0_off
        name: "Gym Lights 0 Off"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights0_off

      - id: gym_lights1_off
        name: "Gym Lights 1 Off"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights1_off

      - id: gym_lights2_off
        name: "Gym Lights 2 Off"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights2_off

      - id: gym_lights3_off
        name: "Gym Lights 3 Off"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights3_off

      - id: gym_lights4_off
        name: "Gym Lights 4 Off"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights4_off

      - id: gym_lights5_off
        name: "Gym Lights 5 Off"
        icon: 'mdi:light'

        on_turn_on:
          then:
            - delay: 3s
            - switch.turn_off: gym_lights5_off

