esphome:
  name: onair1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "zFq6NO4iVzLq2r7ZSduuU/58SVlJklP90LZ+cQOYwCs="

ota:
  password: "0b007ee5f61b777bf1ac1de55a5bb29a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Onair1 Fallback Hotspot"
    password: "nohorvSGFZlG"

captive_portal:

sensor:
  - platform: wifi_signal
    name: "OnAir1 WiFi"
    update_interval: 60s
    
binary_sensor:
  - platform: homeassistant
    id: vmix_on_air
    entity_id: binary_sensor.vmix_on_air
    on_press:
      then:
        - switch.turn_on: onair1_light
    on_release:
      then:
        - switch.turn_off: onair1_light   

switch:
  - platform: gpio
    pin: 12
    name: "OnAir1 Light"
    id: onair1_light
    icon: "mdi:light"

