esphome:
  name: onair2

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Q3Mpne5aCTxVaKB0ewHo4+h6mDDomcxVWFD+JkiGxNM="

ota:
  password: "a214ae6361c37e0dd335de223b9fbcd2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Onair2 Fallback Hotspot"
    password: "9JFRcycK0uAU"

captive_portal:
    
sensor:
  - platform: wifi_signal
    name: "OnAir2 WiFi"
    update_interval: 60s
    
binary_sensor:
  - platform: homeassistant
    id: vmix_on_air
    entity_id: binary_sensor.vmix_on_air
    on_press:
      then:
        - switch.turn_on: onair2_light
    on_release:
      then:
        - switch.turn_off: onair2_light   

switch:
  - platform: gpio
    pin: 12
    name: "OnAir2 Light"
    id: onair2_light
    icon: "mdi:light"

